# Generated by Django 6.0.8 on 2026-09-13 17:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("adapter", models.CharField(max_length=40)),
                ("external_id", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=1000)),
                ("title", models.CharField(max_length=300)),
                ("vin", models.CharField(blank=True, db_index=True, max_length=17)),
                ("year", models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ("mileage", models.PositiveIntegerField(blank=True, null=True)),
                ("fuel", models.CharField(blank=True, max_length=30)),
                ("power_hp", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("colour", models.CharField(blank=True, max_length=60)),
                ("seller", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("images", models.JSONField(default=list)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("original_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("previous_price", models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ("price_changed_at", models.DateTimeField(null=True)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("identity_locked", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("adapter", models.CharField(default="mobile_bg", max_length=40)),
                ("url", models.URLField(max_length=1000, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("make", models.CharField(default="Audi", max_length=30)),
                ("model", models.CharField(default="Q8", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="ScrapeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Complete"),
                            ("partial", "Incomplete"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=12,
                    ),
                ),
                ("pages", models.PositiveIntegerField(default=0)),
                ("seen", models.PositiveIntegerField(default=0)),
                ("created", models.PositiveIntegerField(default=0)),
                ("changed", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="tracker.source",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("missing_runs", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tracker.scraperun"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tracker.listing",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracker.source"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="listing",
            name="sources",
            field=models.ManyToManyField(
                related_name="listings", through="tracker.SourceListing", to="tracker.source"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listings",
                to="tracker.vehicle",
            ),
        ),
        migrations.CreateModel(
            name="GroupingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("action", models.CharField(max_length=30)),
                ("listing_ids", models.JSONField(default=list)),
                ("previous_vehicle_ids", models.JSONField(default=list)),
                ("reason", models.CharField(max_length=200)),
                (
                    "target_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tracker.vehicle"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DuplicateCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                ("reasons", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Review"),
                            ("merged", "Merged"),
                            ("rejected", "Different cars"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_a",
                        to="tracker.listing",
                    ),
                ),
                (
                    "b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_b",
                        to="tracker.listing",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("a", "b"), name="unique_candidate_pair"),
                    models.CheckConstraint(
                        condition=models.Q(("a__lt", models.F("b"))), name="ordered_candidate_pair"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("price_eur", models.DecimalField(decimal_places=2, max_digits=12)),
                ("original_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="tracker.listing",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="tracker.scraperun",
                    ),
                ),
            ],
            options={
                "ordering": ["observed_at", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("listing", "run"), name="one_observation_per_run"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sourcelisting",
            constraint=models.UniqueConstraint(
                fields=("source", "listing"), name="unique_source_listing"
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.UniqueConstraint(
                fields=("adapter", "external_id"), name="unique_site_listing"
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_price__gt", 0)), name="positive_current_price"
            ),
        ),
    ]
