# Generated by Django 6.0.8 on 2026-09-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="price_note",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
